repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
  - repo: git@github.com:PyCQA/autoflake.git
    rev: v2.1.1
    hooks:
    -   id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        'types': [python]
        require_serial: true
        args: [ '--in-place', '--remove-all-unused-imports' ]
  - repo: git@github.com:PyCQA/isort.git
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: git@github.com:psf/black.git
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: git@github.com:pre-commit/mirrors-mypy.git
    rev: v0.942
    hooks:
      - id: mypy
        additional_dependencies: [types_requests]
  - repo: git@github.com:PyCQA/bandit.git
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["--configfile",  "bandit.yaml"]