version: "3"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    env_file: .env
    networks:
      - app-network
  backend:
    env_file: .env
    environment:
       - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    command: bash -c "alembic upgrade head && uvicorn app.backend.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  # nginx:
  #   depends_on:
  #     - backend
  #     - client
  #   restart: always
  #   build:
  #     dockerfile: app/frontend/Dockerfile
  #     context: ./nginx
  #   ports:
  #     - "3050:80"
  # client:
  #   stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   build:
  #     dockerfile: app/frontend/Dockerfile
  #     context: ./client
  #   volumes:
  #     - /app/frontend/node_modules
  #     - ./client:/app

networks:
   app-network:
     driver: bridge