version: "3"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    env_file: .env
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_SERVER=db
    #   - POSTGRES_DB=test_db
  backend:
    env_file: .env
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    command: bash -c "alembic upgrade head && uvicorn app.backend.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
