version: 2.1

parameters:
  stage-name:
    type: string
    default: "tests-<< pipeline.number >>"

orbs:
  python: circleci/python@2.1.1

jobs:
  black:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages:
          args: -d black
          pkg-manager: pipenv
      - run: pipenv run black --version
      - run:
          command: |
            pipenv run black --check app --line-length=79
          name: Black it

  linter:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages:
          args: -d flake8 flake8-print
          pkg-manager: pipenv
      - run: pipenv run flake8 --version
      - run:
          command: |
            pipenv run flake8 -v app
          name: Lint it
  unit-tests:
    environment:
      TESTING_ENV: "true"
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Setup VirtualEnv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest tests/test.py


workflows:
  main:
    jobs:
      - black
      - linter
      - unit-tests:
          requires:
            - black
            - linter