"""Change date_added to date in Event

Revision ID: 4bb7f8887bfb
Revises: 64c8352417d1
Create Date: 2024-05-28 21:07:33.899848

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "4bb7f8887bfb"
down_revision = "64c8352417d1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events", "date_added", nullable=False, new_column_name="date"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
