"""Add tables

Revision ID: 64c8352417d1
Revises: 5e59e77e5b88
Create Date: 2023-05-17 15:08:24.893926

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "64c8352417d1"
down_revision = "5e59e77e5b88"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "events",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("happened", sa.Boolean(), nullable=True),
        sa.Column("date_added", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_table(
        "notes",
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("done", sa.Boolean(), nullable=True),
        sa.Column("date_added", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("note_id"),
        sa.UniqueConstraint("note_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notes")
    op.drop_table("events")
    op.drop_table("users")
    # ### end Alembic commands ###
